dist: trusty
sudo: required
language: node_js
node_js:
  - "12"
  - "11"

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "ryderbrooks-github"
    token:
      secure: $SONAR_TOKEN

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test:dist
  - npm run lint
  - npm run test:src:coverage


after_script:
  - sonar-scanner

after_success:
  - npm run typedoc
  - npm pack


deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: lib.tgz
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: ryderbrooks@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true

